# Generated by Django 4.1.1 on 2022-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
