# Generated by Django 4.1.1 on 2022-09-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='catgoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
